### ISSUE TITLE
Error on Windows command & argument with spaces

### ISSUE THREAD

**Issue by rockResolve** [skywind3000/atom-shell-commands#1]
How do I enter a windows command and an argument with embedded spaces
e.g.
          name: "grepWin"
          command: 'C:/Program Files/grepWin/grepWin.exe'
          arguments: [
              "/searchFor: find me"
          ]

ouput:
["C:/Program Files/grepWin/grepWin.exe","/searchfor: find me"]
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

I tried all sorts of escaping (double, single quotes, cmd ^), but nothing worked.

Possible fix:
The last comment in https://github.com/nodejs/node-v0.x-archive/issues/25895 seems to suggest it is the actual execute at fault. 
Deprecated win-spawn's successor cross-spawn-asnyc spawn appears to address the problem as the above link suggested.

**Comment by skywind3000** [comment]
thanks, I will check that as soon as I get to my pc

**Comment by skywind3000** [comment]
Issue fixed: because I was using an module 'win-spawn' (cross platform spawn) which is really out-of-date, and everything seems alright now when I switched to built-in child_process.spawn in node.js standard module directly.

Could you please give it a try by updating atom-shell-commands to the latest version (1.3.12) and comment here whether it solved your problem ?

**Comment by rockResolve** [comment]
Yes, it now executes commands with embedded spaces correctly.

FYI It does not handle embedded spaces in parameters, but silently drops everything after a space.
But I don't need this right now.
